### ISSUE TITLE
bug: 0324. Wiggle Sort II

### ISSUE THREAD

**Issue by zangbianxuegu** [Hongbo-Miao/leetcode#1]
https://github.com/Hongbo-Miao/leetcode/blob/a64f2b723c9a9c4553fa0f083a88e914ec41760d/JavaScript/0324.%20Wiggle%20Sort%20II.js#L50

It should be `(1 + 2 * i) % (len | 1)`

**Comment by hongbo-miao** [comment]
Thanks @zangbianxuegu ! Just saw it. Fixed by https://github.com/Hongbo-Miao/leetcode/commit/629909b0a3e797c2e0481200e14761146c010171
