### ISSUE TITLE
`if (word[i] === '.')` should has it's return, or it will be return undefined

### ISSUE THREAD

**Issue by zangbianxuegu** [Hongbo-Miao/leetcode#2]
https://github.com/Hongbo-Miao/leetcode/blob/38184b4bfd536fb3d67f3f5de41cd59a8c33fc89/JavaScript/0211.%20Add%20and%20Search%20Word%20-%20Data%20structure%20design.js#L53

I think it should be like this:
```js
let res = false
for (let j = 0; j < 26; j++) {
  const c = String.fromCharCode(97 + j); // 97 -> 'a'
  if (match(node[c], i + 1)) res = true;
}
return res
```

**Comment by hongbo-miao** [comment]
Thanks @zangbianxuegu !
Fixed by https://github.com/Hongbo-Miao/leetcode/commit/ced7613ed3cdba2aa2a34a35822212547a99c3d3
